//
//  DevCaches.swift
//  DiskTracker
//
//  Known developer-tool cache folders, measured with the scan engine.
//
//  Everything here is regenerated by its tool on next use, except Xcode
//  Archives (signed builds and crash symbols), which is flagged as a warning.
//  Folders the app should only measure — trashing them would destroy state,
//  not cache — carry a terminal command instead.
//

import Foundation

enum DevTool: String, CaseIterable, Sendable {
    case homebrew = "Homebrew"
    case javascript = "JavaScript"
    case python = "Python"
    case rust = "Rust"
    case gradle = "Gradle"
    case android = "Android"
    case xcode = "Xcode"
    case simulator = "Simulator"
}

struct DevCache: Hashable, Sendable {
    let tool: DevTool
    let label: String
    /// Relative to the real home folder.
    let relativePath: String
    /// The tool's own cleanup command, shown for the user to run themselves:
    /// the sandbox forbids launching anything outside the bundle.
    var command: String?
    /// Why this one is not like the others — shown beside the row.
    var warning: String?
    /// False for folders that are state, not cache — measured only.
    var trashable = true

    var path: String { ScopedAccess.realHome + "/" + relativePath }

    static let all: [DevCache] = [
        DevCache(tool: .homebrew, label: "Downloads", relativePath: "Library/Caches/Homebrew",
                 command: "brew cleanup --prune=all"),
        DevCache(tool: .javascript, label: "npm cache", relativePath: ".npm/_cacache",
                 command: "npm cache clean --force"),
        DevCache(tool: .javascript, label: "Yarn cache", relativePath: "Library/Caches/Yarn",
                 command: "yarn cache clean"),
        DevCache(tool: .javascript, label: "pnpm store", relativePath: "Library/pnpm/store",
                 command: "pnpm store prune"),
        DevCache(tool: .python, label: "pip cache", relativePath: "Library/Caches/pip",
                 command: "pip3 cache purge"),
        DevCache(tool: .rust, label: "Cargo registry cache", relativePath: ".cargo/registry/cache"),
        DevCache(tool: .rust, label: "Cargo git checkouts", relativePath: ".cargo/git"),
        DevCache(tool: .gradle, label: "Caches", relativePath: ".gradle/caches"),
        DevCache(tool: .gradle, label: "Daemon logs", relativePath: ".gradle/daemon",
                 command: "gradle --stop"),
        DevCache(tool: .gradle, label: "Wrapper distributions", relativePath: ".gradle/wrapper"),
        DevCache(tool: .android, label: "Cache", relativePath: ".android/cache"),
        DevCache(tool: .xcode, label: "DerivedData", relativePath: "Library/Developer/Xcode/DerivedData"),
        DevCache(tool: .xcode, label: "Xcode cache", relativePath: "Library/Caches/com.apple.dt.Xcode"),
        DevCache(tool: .xcode, label: "iOS Device Support",
                 relativePath: "Library/Developer/Xcode/iOS DeviceSupport"),
        DevCache(tool: .xcode, label: "Swift Package cache", relativePath: "Library/Caches/org.swift.swiftpm"),
        DevCache(tool: .xcode, label: "Archives", relativePath: "Library/Developer/Xcode/Archives",
                 warning: "Holds your signed builds and their .dSYM crash symbols. Not regenerated."),
        DevCache(tool: .simulator, label: "Simulator caches", relativePath: "Library/Developer/CoreSimulator/Caches"),
        DevCache(tool: .simulator, label: "Simulator devices", relativePath: "Library/Developer/CoreSimulator/Devices",
                 command: "xcrun simctl delete unavailable", trashable: false),
    ]
}

enum DevCaches {
    struct Measured: Sendable, Identifiable {
        let cache: DevCache
        /// Childless root: the size is all the list needs, and a DerivedData
        /// tree is not worth holding.
        let node: DiskNode
        var id: String { cache.relativePath }
    }

    /// Measures every cache that exists, largest first. Nil without a home
    /// grant. Blocking — one engine run per folder; call off the main thread.
    static func measure() -> [Measured]? {
        guard let grant = ScopedAccess.access(path: ScopedAccess.realHome) else { return nil }
        defer { withExtendedLifetime(grant) {} }

        let scanner = DirectoryScannerBridge()
        let config = ScanConfig(excludeHiddenFiles: false)
        return DevCache.all
            .filter { FileManager.default.fileExists(atPath: $0.path) }
            .compactMap { cache in
                guard var node = scanner.scan(path: cache.path, config: config) else { return nil }
                node.children = nil
                return Measured(cache: cache, node: node)
            }
            .sorted { $0.node.totalPhysicalSize > $1.node.totalPhysicalSize }
    }
}
